[theme]
# Color de acento 
primaryColor = "#BC69AA"

# Fondo principal 
backgroundColor = "#FFFFFF"

# Fondo de tarjetas y sidebar 
secondaryBackgroundColor = "#F8F1F4

# Texto principal
textColor = "#2C2C2C"

font = "sans serif"